info:
  author: false
  homepage: false
  banner: "/*!\n * <%= package %> - created by <%= author %>\n * @build <%= timestamp %>\n * @link <%= homepage %>\n */\n"
  package: false

global:
  mergeConfigFromPackages:
    - src
    - .src
    - _src
    - Source
    - LocalPackages
    - DistributionPackages
  notifications: false
  browserSync:
    enable: true
    proxy: '127.0.0.1:8081'
    proxyRootFolder: 'https://'
    open: false
    xip: false
  chmod:
    owner:
      read: true
      write: true
      execute: false
    group:
      read: true
      write: false
      execute: false
    others:
      read: true
      write: false
      execute: false

root:
  base: null
  src: 'Resources/Private'
  dest: 'Resources/Public'
  watch: 'Resources/Private/**'
  dontWatch: 'Resources/Private/Templates/**'
  inlinePath: 'Templates/InlineAssets'

packages: {}

tasks:
  clean:
    - Assets
    - Styles
    - Scripts
    - '*.css'
    - '*.js'
    - '*.map'
    - '*.js.br'
    - '*.js.gz'
    - '*.css.br'
    - '*.css.gz'
  css:
    custom: false
    src: Assets
    dest: Styles
    file: null
    sourceMaps: true
    extensions:
      - sass
      - scss
      - css
    sass:
      imagePath: Assets
      precision: 10
      sourceComments: false
      outputStyle: expanded
      includePaths:
        - './Packages/Sites/'
        - './Packages/Carbon/'
        - './Packages/Plugins/'
        - './node_modules/'
    postcss:
      activateRtlCss: false
      assets:
        loadPaths:
          # Need to be a single directory
          dest: Assets
          # Need to be an array
          src:
            - Sprite
            - Fusion
          # Relative path from dest to src directory. This is needed for resolve inline assets
          srcRelativeToDest: ../../Private/
        private:
          cachebuster: false
          baseUrl: /_Resources/Static/Packages/%KEY%
        public:
          cachebuster: false
      momentumScrolling:
        - scroll
        - auto
        - inherit
      presetEnv:
        stage: 2
      short:
        skip: x
      mqpacker:
        sort: true
      pxtorem:
        rootValue: 16
        unitPrecision: 5
        propList:
          - font
          - font-size
          - line-height
          - letter-spacing
        selectorBlackList: []
        replace: true
        mediaQuery: false
        minPixelValue: 0
      autoprefixer:
        grid: true
      cssnano:
        reduceIdents: false
        zindex: false
        discardComments:
          removeAll: true
      imagemin:
        gifsicle: {}
        jpegtran: {}
        optipng: {}
        svgo: {}
    cssbeautifyOptions:
      indent: '  '
      autosemicolon: true
  scss: true
  js:
    custom: false
    src: Assets
    dest: Scripts
    file: null
    sourceMaps: true
    extensions:
      - js
      - jsx
    compiler: Babel
    babel: {}
    buble:
      objectAssign: 'Object.assign'
    rollup:
      enable: true
      format: iife # Available formats are amd, cjs, es6, iife or umd
      plugins:
        builtins: true
        nodeResolve:
          module: true
          jsnext: true
          main: true
          browser: true
        includePaths:
          include: {}
          paths:
            - COMPOSER_PACKAGES
            - Packages/Carbon
            - Packages/Plugins
          external: []
          extensions:
            - .js
            - .json
            - .jsx
        commonjs:
          exclude: node_modules/process-es6/**
          include:
            - node_modules/**
        amd: false
        terser:
          warnings: false
          mangle: true
          module: false
  optimizeImages:
    custom: false
  images:
    custom: false
    src: Images
    dest: Assets
    watchOnlySrc: true
    extensions:
      - jpg
      - jpeg
      - png
      - svg
      - gif
      - ico
  fonts:
    custom: false
    src: Fonts
    dest: Assets
    watchOnlySrc: true
    extensions:
      - woff2
      - woff
      - eot
      - ttf
      - svg
  static:
    custom: false
    src: Static
    dest: Assets
    watchOnlySrc: true
    extensions:
      - '*'
  optimizeSvg: src
  svgSprite:
    custom: false
    src: Sprite
    dest: Assets
    watchOnlySrc: true
    svgo: {}
    extensions:
      - svg
    config:
      # If set to false no private Sprite will be rendered
      private:
        mode:
          inline: true
          symbol:
            inline: true
            dest: ''
            sprite: '%srcFolderName%.svg'
            bust: false
      # If set to false no public Sprite will be rendered
      public:
        svg:
          xmlDeclaration: true
          doctypeDeclaration: false
        mode:
          symbol:
            dest: ''
            sprite: '%srcFolderName%.svg'
            bust: false
  showConfig: true
  pipeline:
    - build
    - optimizeImages
