info:
  author: false
  homepage: false
  banner: "/*!\n * <%= package %> - created by <%= author %>\n * @build <%= timestamp %>\n * @link <%= homepage %>\n */\n"
  package: false

global:
  mergeConfigFromPackages:
    - .src
  notifications: false
  browserSync:
    enable: true
    proxy: "127.0.0.1:8081"
    proxyRootFolder: "https://"
    open: false
    xip: false
  chmod:
    owner:
      read: true
      write: true
      execute: false
    group:
      read: true
      write: false
      execute: false
    others:
      read: true
      write: false
      execute: false

root:
  base: "./.src/"
  src: "Resources/Private"
  dest: "Resources/Public"
  watch: "Resources/Private/**"
  dontWatch: "Resources/Private/Templates/**"
  inlinePath: "Templates/InlineAssets"
  inlineAssets: false

packages: {}

tasks:
  clean:
    - Assets
    - Styles
    - Scripts
    - Modules
    - "*.js"
    - "*.js.br"
    - "*.js.gz"
    - "*.mjs"
    - "*.mjs.br"
    - "*.mjs.gz"
    - "*.css"
    - "*.css.br"
    - "*.css.gz"
    - "*.map"
  css:
    src: Assets
    dest: Styles
    file: null
    extensions:
      - sass
      - scss
      - css
    sass:
      imagePath: "Assets"
      precision: 10
      sourceComments: true
      includePaths:
        - "./Packages/Sites/"
        - "./Packages/Plugins/"
        - "./node_modules/"
    postcss:
      activateRtlCss: false
      assets:
        loadPaths:
          - "Assets"
          - "../Private/Sprite"
          - "../Private/Fusion"
        cachebuster: false
      magicAnimations:
        atRoot: true
      pseudoelements:
        single: true
        selectors:
          - "before"
          - "after"
          - "first-letter"
          - "first-line"
      short:
        border:
          skip: x
        border-radius:
          skip: x
        color:
          skip: x
        font-size:
          skip: x
        position:
          skip: x
        size:
          skip: x
        spacing:
          skip: x
      rucksack:
        fallbacks: false
      mqpacker:
        sort: true
      pxtorem:
        rootValue: 16
        unitPrecision: 5
        propList:
          - font
          - font-size
          - line-height
          - letter-spacing
        selectorBlackList: []
        replace: true
        mediaQuery: false
        minPixelValue: 0
      autoprefixer:
        grid: true
      cssnano:
        reduceIdents: false
        zindex: false
        discardComments:
          removeAll: true
      fixes:
          preset: safe
      imagemin:
          gifsicle: {}
          jpegtran: {}
          optipng: {}
          svgo: {}
    cssbeautifyOptions:
        indent: "  "
        autosemicolon: true
  scss: true
  scssLint: true
  jsLint: true
  mjs:
    src: Assets
    dest: Modules
    file: null
    extensions:
      - mjs
      - mjsx
    compiler: Babel
    babel: {}
    buble:
      objectAssign: "Object.assign"
    rollup:
      enable: true
      format: umd # Available formats are amd, cjs, es6, iife or umd
      plugins:
        nodeResolve:
          module: true
          jsnext: true
          main: true
          browser: true
        includePaths:
          include: {}
          paths:
            - ""
            - Packages/Plugins
          external: []
          extensions:
            - .js
            - .mjs
            - .json
            - .jsx
        commonjs:
          exclude: node_modules/process-es6/**
          include:
            - node_modules/**
        amd: false
  js:
    src: Assets
    dest: Scripts
    file: null
    extensions:
      - js
      - jsx
    compiler: Babel
    babel: {}
    buble:
      objectAssign: "Object.assign"
    rollup:
      enable: true
      format: iife # Available formats are amd, cjs, es6, iife or umd
      plugins:
        nodeResolve:
          module: true
          jsnext: true
          main: true
          browser: true
        includePaths:
          include: {}
          paths:
            - ""
            - Packages/Plugins
          external: []
          extensions:
            - .js
            - .mjs
            - .json
            - .jsx
        commonjs:
          exclude: node_modules/process-es6/**
          include:
            - node_modules/**
        amd: false
  images:
    src: Images
    dest: Assets
    watchOnlySrc: true
    extensions:
      - jpg
      - jpeg
      - png
      - svg
      - gif
      - ico
  fonts:
    src: Fonts
    dest: Assets
    watchOnlySrc: true
    extensions:
      - woff2
      - woff
      - eot
      - ttf
      - svg
  static:
    src: Static
    dest: Assets
    watchOnlySrc: true
    extensions:
      - "*"
  optimizeSvg: src
  svgSprite:
    src: Sprite
    dest: Assets
    watchOnlySrc: true
    svgo: {}
    extensions:
      - svg
    config:
      private:
        mode:
          inline: true
          symbol:
            inline: true
            dest: ""
            sprite: "%srcFolderName%.svg"
            bust: false
      public:
        svg:
          xmlDeclaration: true
          doctypeDeclaration: false
        mode:
          symbol:
            dest: ""
            sprite: "%srcFolderName%.svg"
            bust: false
  compress:
    brotli:
      skipLarger: true
      quality: 11
    zopfli:
      format: gzip
      numiterations: 15
      blocksplitting: true
  pipeline:
    - build
    - optimizeImages
    - compress
