echo "${GREEN}Update files on root${NC}"
. "$PWD/Build/Gulp/Distribution/Helper/CopyFiles.sh"
echo "If you want to merge json files, you need to install following package globally:"
echo "${RED}https://www.npmjs.com/package/json${NC}"
echo "You can install it with this command: ${RED}yarn global add json${NC}"
