exclude: 'node_modules/**'

linters:
  BorderZero:
    enabled: false
  ColorVariable:
    enabled: false
  ColorKeyword:
    enabled: false
  Comment:
    enabled: false
  Indentation:
    character: tab
    width: 1
  LeadingZero:
    enabled: false
  NameFormat:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: false
  PropertySpelling:
    enabled: false
  SpaceAfterVariableName:
    enabled: false
  SelectorFormat:
    enabled: false
  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%', 'fr']                                     # Other
    properties: {}

  NestingDepth:
    max_depth: 4
  SelectorDepth:
    max_depth: 4
